package resource

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	Repo        *string  `json:",omitempty"`
	Owner       *string  `json:",omitempty"`
	Token       *string  `json:",omitempty"`
	PayloadURL  *string  `json:",omitempty"`
	ContentType *string  `json:",omitempty"`
	Secret      *string  `json:",omitempty"`
	InsecureSSL *bool    `json:",omitempty"`
	Events      []string `json:",omitempty"`
	Active      *bool    `json:",omitempty"`
	WebhookURL  *string  `json:",omitempty"`
}
